/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./components/icons/Calendar.vue')['default']
    Check: typeof import('./components/icons/Check.vue')['default']
    CheckInBox: typeof import('./components/icons/CheckInBox.vue')['default']
    Chevron: typeof import('./components/icons/Chevron.vue')['default']
    Clock: typeof import('./components/icons/Clock.vue')['default']
    Close: typeof import('./components/icons/Close.vue')['default']
    Edit: typeof import('./components/icons/Edit.vue')['default']
    EditModal: typeof import('./components/todo/EditModal.vue')['default']
    Filter: typeof import('./components/icons/Filter.vue')['default']
    FilterModal: typeof import('./components/modal/FilterModal.vue')['default']
    FilterOptions: typeof import('./components/todo/FilterOptions.vue')['default']
    Flag: typeof import('./components/icons/Flag.vue')['default']
    FlagCross: typeof import('./components/icons/FlagCross.vue')['default']
    FlagFilled: typeof import('./components/icons/FlagFilled.vue')['default']
    Grid: typeof import('./components/icons/Grid.vue')['default']
    List: typeof import('./components/icons/List.vue')['default']
    Modal: typeof import('./components/common/Modal.vue')['default']
    Moon: typeof import('./components/icons/Moon.vue')['default']
    Notes: typeof import('./components/icons/Notes.vue')['default']
    Plus: typeof import('./components/icons/Plus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Save: typeof import('./components/icons/Save.vue')['default']
    Sort: typeof import('./components/icons/Sort.vue')['default']
    Subtask: typeof import('./components/icons/Subtask.vue')['default']
    Sun: typeof import('./components/icons/Sun.vue')['default']
    ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
    TodoInput: typeof import('./components/todo/TodoInput.vue')['default']
    TodoList: typeof import('./components/todo/TodoList.vue')['default']
    Trash: typeof import('./components/icons/Trash.vue')['default']
    XCalander: typeof import('./components/common/XCalander.vue')['default']
    XCheckbox: typeof import('./components/common/XCheckbox.vue')['default']
    XRadioButton: typeof import('./components/common/XRadioButton.vue')['default']
  }
}
