/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Check: typeof import('./components/icons/Check.vue')['default']
    Checkbox: typeof import('./components/todo/Checkbox.vue')['default']
    Copy: typeof import('./components/Copy.vue')['default']
    Filter: typeof import('./components/icons/Filter.vue')['default']
    FilterOptions: typeof import('./components/todo/FilterOptions.vue')['default']
    Flag: typeof import('./components/icons/Flag.vue')['default']
    FlagCross: typeof import('./components/icons/FlagCross.vue')['default']
    FlagFilled: typeof import('./components/icons/FlagFilled.vue')['default']
    Github: typeof import('./components/Github.vue')['default']
    Grid: typeof import('./components/icons/Grid.vue')['default']
    Input: typeof import('./components/todo/Input.vue')['default']
    List: typeof import('./components/icons/List.vue')['default']
    Modal: typeof import('./components/common/modal.vue')['default']
    Plus: typeof import('./components/icons/Plus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sort: typeof import('./components/icons/Sort.vue')['default']
    TodoInput: typeof import('./components/todo/TodoInput.vue')['default']
    TodoList: typeof import('./components/todo/TodoList.vue')['default']
    Trash: typeof import('./components/icons/Trash.vue')['default']
    XTooltip: typeof import('./components/common/XTooltip.vue')['default']
  }
}
